# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = "open-temporary"
  s.version = "1.0.2"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Urabe, Shyouhei"]
  s.date = "2012-09-06"
  s.description = "A variation of tempfile standard lib, that actually creates a File instance."
  s.email = "shyouhei@ruby-lang.org"
  s.extensions = ["ext/open_temporary/extconf.rb"]
  s.extra_rdoc_files = [
    "LICENSE.txt",
    "README.rdoc"
  ]
  s.files = [
    ".document",
    ".rspec",
    "Gemfile",
    "Gemfile.lock",
    "LICENSE.txt",
    "README.rdoc",
    "Rakefile",
    "VERSION",
    "ext/open_temporary/.gitignore",
    "ext/open_temporary/extconf.rb",
    "ext/open_temporary/open_temporary.c",
    "lib/open-temporary.rb",
    "open-temporary.gemspec",
    "spec/open-temporary_spec.rb",
    "spec/spec_helper.rb"
  ]
  s.homepage = "http://github.com/shyouhei/open-temporary"
  s.licenses = ["MIT"]
  s.require_paths = ["lib"]
  s.rubygems_version = "1.8.24"
  s.summary = "A variant of Tempfile that makes File instead"

  if s.respond_to? :specification_version then
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_development_dependency(%q<rake>)
      s.add_development_dependency(%q<rspec>)
      s.add_development_dependency(%q<yard>)
      s.add_development_dependency(%q<rdoc>)
      s.add_development_dependency(%q<bundler>)
      s.add_development_dependency(%q<jeweler>)
      s.add_development_dependency(%q<simplecov>)
    else
      s.add_dependency(%q<rake>)
      s.add_dependency(%q<rspec>)
      s.add_dependency(%q<yard>)
      s.add_dependency(%q<rdoc>)
      s.add_dependency(%q<bundler>)
      s.add_dependency(%q<jeweler>)
      s.add_dependency(%q<simplecov>)
    end
  else
    s.add_dependency(%q<rake>)
    s.add_dependency(%q<rspec>)
    s.add_dependency(%q<yard>)
    s.add_dependency(%q<rdoc>)
    s.add_dependency(%q<bundler>)
    s.add_dependency(%q<jeweler>)
    s.add_dependency(%q<simplecov>)
  end
end

